apiVersion: apps/v1
kind: Deployment
metadata:
  name: task2-deployment
  labels: 
    app: task2-app
    env: prod
    owner: aitork
spec:
  replicas: 3
  selector:
    matchLabels:
      project: aitork-task2
  template:
    metadata:
      labels:
        project: aitork-task2
    spec:
      containers:
        - name: back2
          image: aitork/kubeback:latest
          ports:
            - containerPort: 8080
        - name: front2
          image: aitork/kubefront:latest
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: service2
  labels:
    env: prod
    owner: aitork
spec:
  type: LoadBalancer
  selector:
    project: aitork-task2
  ports:
    - name: app-listener2
      protocol : TCP
      port: 8080
      targetPort: 8080
      
    - name: app-listener3
      protocol: TCP
      port: 8081
      targetPort: 8081