apiVersion: apps/v1
kind: Deployment
metadata:
  name: task1-deployment
  labels: 
    app: task1-app
    env: prod
    owner: aitork
spec:
  replicas: 3
  selector:
    matchLabels:
      project: aitork-task1
  template:
    metadata:
      labels:
        project: aitork-task1
    spec:
      containers:
        - name: back
          image: aitork/kubeback:latest
          ports:
            - containerPort: 8080

...
apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    env: prod
    owner: aitork
spec:
  type: LoadBalancer
  selector:
    project: aitork-task1
  ports:
    - name: app-listener1
      protocol : TCP
      port: 8080
      targetPort: 8080